---
title: "H_Simulation_Analysis"
author: "Tyler M. Wiles"
date: "2025-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Description



# Libraries and Data Management

```{r Libraries and Data Management}

options(scipen = 999)
rm(list=ls())

library(data.table)
library(here)
library(ggplot2)
library(ggridges)

files = list.files(path = here::here('DATA', 'H_Simulation'), pattern = "^H_S.*\\.csv$", full.names = TRUE)
dat = rbindlist(lapply(files, data.table::fread))

setnames(dat, old = c('h.original', 'h.test.random', 'h.test.contiguous'),
         new = c('original', 'random', 'contiguous'))

dat.long = melt(dat,
                measure.vars = tail(names(dat), 3),
                variable.name = "data.version",
                value.name   = "h.value")

dat.long$drops = dat.long$drops * 100 # Change to percent

# Factors
dat.long$id = factor(dat.long$id)
dat.long$strides = factor(dat.long$strides)
dat.long$drops = factor(dat.long$drops)
dat.long$strides.cut = factor(dat.long$strides.cut)
dat.long$strides.new.length = dat.long$strides.new.length
dat.long$h.target = factor(dat.long$h.target)

```

# Plots

```{r Plots}

ggplot(dat.long, aes(x = h.value, y = h.target, fill = data.version)) +
  theme_classic() +
  geom_density_ridges(color = "black", scale = 1, quantile_lines = T, quantile_fun = mean) +
  scale_fill_manual(values = c("original" = "black",
      "random" = scales::alpha("blue", 0.1),
      "contiguous" = scales::alpha("red", 0.1)),
    name = "Data Version") +
  scale_x_continuous(limits = c(0, 1),
                     breaks = seq(0, 1, 0.1)) +
  labs(x = "Expected Hurst Exponent",
       y = "Density of Hurst Exponents") +
  facet_grid(rows = vars(drops))





means <- dat.long[, .(mean_value = mean(h.value, na.rm = TRUE)),
                  by = .(data.version, h.target)]

ggplot(dat.long, aes(x = h.value, fill = data.version)) +
  theme_classic() +
  geom_density(alpha = 0.6, color = "black") +
  geom_vline(data = means,
             aes(xintercept = mean_value, color = data.version),
             linewidth = 1) +
  scale_fill_manual(values = c("original" = "black",
      "random" = scales::alpha("blue", 0.5),
      "contiguous" = scales::alpha("red", 0.5)),
    name = "Data Version") +
  scale_color_manual(values = c("original" = "black",
      "random" = "blue",
      "contiguous" = "red"),
    guide = "none") +
  scale_x_continuous(limits = c(0, 1),
                     breaks = seq(0, 1, 0.1)) +
  labs(x = "Expected Hurst Exponent",
       y = "Density of Hurst Exponents") +
  facet_grid(rows = vars(h.target),
             cols = vars(drops))












```